language: python

python: 3.8

sudo: required

cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.pyenv"

branches:
  except:
    - wintest

matrix:
  include:
    # recent libcurl
    - os: linux
      env: TOX_ENV=py38-recent-libcurl
      python: 3.8

    # qa
    - os: linux
      env: TOX_ENV=qa
      python: 3.8

    # linux (pycurl transport)
    - os: linux
      env: TOX_ENV=py36
      python: 3.6
    - os: linux
      env: TOX_ENV=py37
      python: 3.7
    - os: linux
      env: TOX_ENV=py38
      python: 3.8
    - os: linux
      env: TOX_ENV=py39
      python: 3.9

     # urllib3 transport
    - os: linux
      env: TOX_ENV=py36-urllib3
      python: 3.6
    - os: linux
      env: TOX_ENV=py37-urllib3
      python: 3.7
    - os: linux
      env: TOX_ENV=py38-urllib3
      python: 3.8
    - os: linux
      env: TOX_ENV=py39-urllib3
      python: 3.9


    # osx
    - os: osx
      language: generic
      env:
        - TOX_ENV=py36
        - PYENV_VERSION="3.6.0"

    # release (install from pypi)
    - os: linux
      env: TOX_ENV=py3-grab-release
      python: 3.8
  exclude:
    - python: 3.8 # hack to exclude default no-env travis job
  allow_failures:
    - env: TOX_ENV=py36-urllib3
    - env: TOX_ENV=py37-urllib3
    - env: TOX_ENV=py38-urllib3
    - env: TOX_ENV=py39-urllib3
    - env: TOX_ENV=qa

# Enable extra mongodb and redis services on linux
# That does not work on osx (see below custom instructions for osx)
services:
  - mongodb
  - redis-server

install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      ulimit -n 2048 # by default travis osx has "ulimit -n 256"
      brew update
      brew install mongodb
      sudo mkdir -p /data/db
      brew services start mongodb
      brew install redis
      brew services start redis
      brew upgrade pyenv
    fi

before_script:
  # Install custom pyton version on OSX
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      if [[ ! -z "$VIRTUAL_ENV" ]]; then deactivate; fi
      eval "$(pyenv init -)"
      pyenv install --skip-existing "$PYENV_VERSION"
      pyenv global "$PYENV_VERSION"
    fi
  - |
    if [[ "$TOX_ENV" == "py38-recent-libcurl" ]]; then
      mkdir $HOME/curl_files
      cd $HOME/curl_files
      pwd
      wget https://curl.haxx.se/download/curl-7.59.0.tar.gz
      tar -xzf curl-7.59.0.tar.gz
      cd curl-7.59.0
      ./configure --prefix=$HOME/curl_lib
      make
      make install
      cd $HOME/build/lorien/grab
    fi
  # Remove APT pycurl packages
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get remove python-pycurl python3-pycurl;
      sudo apt-get install -y libcurl4-openssl-dev;
    fi
  - python -m pip install -U pip setuptools tox

script:
  # Inject path to recent libcurl library
  - |
    if [[ "$TOX_ENV" == "py38-recent-libcurl" ]]; then
      export LD_LIBRARY_PATH="$HOME/curl_lib/lib"
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      export LDFLAGS="-L/usr/local/opt/openssl/lib"
      export CPPFLAGS="-I/usr/local/opt/openssl/include"
      export PYCURL_SSL_LIBRARY=openssl
    fi
  - tox -e $TOX_ENV

after_success:
  - coveralls
