name: test

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install pycurl
      run: |
        pip install "https://github.com/lorien/pycurl_packages/raw/main/py^Crl-7.44.1-cp310-cp310-win_amd64.whl"

    - name: Run test
      run: |
        python -c "import pycurl"
