name: test

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python: ['3.7', '3.8', '3.9', '3.10']
    steps:

    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}

    - name: Install Ubuntu build dependencies
      if: ${{ startsWith(matrix.os, 'ubuntu') }}
      run: |
        sudo apt-get install libcurl4-openssl-dev libxml2-dev libxslt-dev
    
    - name: Install MacOS build dependencies
      if: ${{ startsWith(matrix.os, 'macos') }}
      run: |
        brew install openssl

    - name: Instal pycurl on MacOS
      if: ${{ startsWith(matrix.os, 'macos') }}
      run: |
        PYCURL_SSL_LIBRARY=openssl LDFLAGS="-L/usr/local/opt/openssl/lib" CPPFLAGS="-I/usr/local/opt/openssl/include" pip install -U --no-cache-dir pycurl

    - name: Install dependencies
      run: |
        pip install -U -r requirements_dev.txt
        pip install -U -e .

    - name: Run tests
      run: |
        coverage run runtest.py --test-all

    - name: Upload coverage results
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        coveralls --service=github
